AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Example using the Custom::SES_Domain CloudFormation custom resource type to provision
  an Amazon SES domain identity and maintain necessary DNS records in Route53

Parameters:
  Domain:
    Type: String
    Description: >
      The domain name you want to provision for Amazon SES (e.g., "corp.example.com").
  CfnSESDomainTemplateURL:
    Type: String
    Description: >
      The S3 url where you have uploaded your copy of aws-cfn-ses-domain.cf.yaml.
    Default: https://s3.amazonaws.com/YOUR_BUCKET_NAME/YOUR_LAMBDA_ZIP_KEY

Resources:
  # Use a nested stack to create the AWS Lambda Function for the Custom::SES_Domain type.
  # This stack's "Arn" output is what you'll need for the custom resource's ServiceToken.
  CfnSESDomain:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref CfnSESDomainTemplateURL

  # Use Custom::SES_Domain to provision a domain identity in SES
  MySESDomain:
    Type: Custom::SES_Domain
    Properties:
      ServiceToken: !GetAtt CfnSESDomain.Outputs.Arn
      # Domain is required; all others are optional
      Domain: !Ref Domain
      EnableReceive: true
      EnableSend: true
      MailFromSubdomain: "mail"
      TTL: "1800"
      CustomDMARC: '"v=DMARC1; p=none; pct=100; sp=none; aspf=r;"'

  # Add the necessary Route 53 DNS records for the SES domain identity.
  # (This assumes you already have a Route 53 hosted zone for Domain;
  # if not, add a Type: AWS::Route53::HostedZone resource to create it.)
  MyRoute53Records:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${Domain}."
      RecordSets: !GetAtt MySESDomain.Route53RecordSets
